### ISSUE TITLE
OSD does not close when switching to HD+ channels. and during recordings is also no OSD present

### ISSUE THREAD

**Issue by haarm** [reufer/rpihddevice#10]
When I switch from a Free to Air channel to an HD+ channel, the OSD no longer closes.
Also, when watching recordings, there is no OSD/progress indicator. This does not occur on ARD or WDR for example.

**Comment by dr-m** [comment]
I just tested all free-to-air DVB-T2 channels that are accessible to me: Yle Teema & Fem HD, MTV3 HD, Yle TV2 HD, Yle TV1 HD. All of them were successfully displaying some subtitles at the time I tested. This is relevant because subtitles use the OSD layer. Nowadays even same-language (Finnish or Swedish) subtitles are often available.

After I reduced my `gpu_mem` in `/boot/config.txt` from 256 megabytes to 128 megabytes, I am unable to see any larger OSD menus. Smaller OSD menus, such as the volume change bar, or the subtitle selection, still worked with `gpu_mem=128`, as do the subtitles (usually 1 or 2 lines of text). The program info that I get by pressing OK during live view would refuse to open (when using the LCARS skin) was already too large to open. The native resolution of my HDMI screen is 1920×1080.

With `gpu_mem=192` everything seemed to work at first, but occasionally, depending on the rate of subtitle updates, the OSD would refuse to open. On one occasion, the MTV3 HD channel would only display OSD subtitles and play audio, but only display a black screen. I guess that the memory used by OSD layers is not being freed immediately. After switching channels a few times between MTV3 HD and Yle Teema & Fem HD, I was able to open the full-screen OSD menu again, and MTV3 HD would start displaying video again. So, it looks like I will need `gpu_mem=256` for reliable operation.

I also shortly tested what happens if I disable the GPU acceleration for the OSD layer when using `gpu_mem=256`. The OSD menu lagged quite a bit, updating maybe once in 1 or 2 seconds. More than 10 button presses were buffered and took effect afterwards.

In summary, I got close to reproducing the "OSD does not show up" issue that I mentioned in #9. It is possibly caused by a GPU memory leak, which my fix of #9 could plug. But I was not able to reproduce anything like your issue (OSD menu refusing to hide).

What is your `gpu_mem` setting in `/boot/config.txt` and what are the rpihddevice settings in the VDR `setup.conf`? Mine are as follows:
```
rpihddevice.AcceleratedOsd = 1
rpihddevice.AdvancedDeinterlacer = 1
rpihddevice.AudioFormat = 2
rpihddevice.AudioPort = 1
rpihddevice.FrameRate = 1
rpihddevice.Resolution = 1
rpihddevice.VideoFraming = 0
```
When the problem occurs, is there any way to clear the OSD layer without restarting VDR? How does the picture look like? Would part of the "ghost" OSD be overwritten if you activate the volume controls (mute, volume up, volume down), or will the OSD just stay frozen? What is your screen resolution? What are your OSD settings? Mine are as follows:
```
OSDAspect = 1.000000
OSDHeight = 1037
OSDHeightP = 0.960000
OSDLanguage = fi_FI
OSDLeft = 19
OSDLeftP = 0.010000
OSDMessageTime = 2
OSDSkin = lcars
OSDTheme = default
OSDTop = 22
OSDTopP = 0.020000
OSDWidth = 1880
OSDWidthP = 0.980000
```

**Comment by dr-m** [comment]
I got a wild idea: Introduce a configuration option to replace the `VG_sARGB_8888` with `VG_sARGB_1555`. That would halve the memory consumption to 2 bytes per pixel. Yes, we would lose translucent subtitles or OSD menus, but I don’t think losing 3 bits per color component would be too bad. This option would allow a smaller `gpu_mem` setting to be used, freeing up some RAM for other uses.

Another thing worth investigating might be if `cOvgThread::DoCmd()` and `cOvgThread::Action()` could be simplified to use a single mutex and two condition variables for ("queue empty" or "queue full"), to avoid any unnecessary delay. Currently it is using a combination of polling and event-based handling. It could be better to invoke `pthread_cond_timedwait()` on the said condition variables.

I see that `ovgosd.c` includes some `ELOG` macro invocations. Unfortunately, I didn’t check any logs when testing this yesterday. @haarm Do you find anything of interest in `/var/log/syslog` or in the output of `journalctl -u vdr`?

**Comment by haarm** [comment]
@dr-m 
I then watched TV yesterday with rpi setting ,and the OSD always closed.
Then I watched recordings, everything worked fine so far.but when I stop recording, the VDR crashes.
I was then yesterday too tired to investigate further.
GPU Mem is with me 256

**Comment by haarm** [comment]
When the VDR then crashes I find this message:

assertion failure:ilclient.c:1759:ilclient_get_handle():comp

**Comment by haarm** [comment]
When I set the resolution to 1920X1080 the VDR does not crash anymore when I stop recording.

**Comment by dr-m** [comment]
@haarm What was your output resolution previously?

Can you produce a stack trace for the crash? Apparently, `ilclient_get_handle()` is being invoked on a null pointer. There are numerous calls to that function via the expansion of the macro `ILC_GET_HANDLE()`. I suspect that some object creation fails due to insufficient GPU memory, and there is not sufficient error handling in the `rpihddevice` code.

I will try to experiment with both my ideas, to see if I could reduce the memory consumption. Curiously, 1920×1080×4 is only 7.91MiB; that is, you could fit more than 32 full-screen layers in the 256 megabytes of GPU memory. (OK, some memory will be needed for fonts and for the video decoding.) Apparently some GPU memory is being freed very lazily somewhere.

**Comment by haarm** [comment]
Oh, ich lese gerade du sprichst deutsch

**Comment by dr-m** [comment]
@haarm Wenn es Dir einfacher ist, kannst Du gerne auf Deutsch schreiben. Für manche Mitleser mag Englisch einfacher sein.

I am only now learning this part of the source code. I noticed a constant `OVG_MAX_OSDIMAGES` (256). I may be misunderstanding something, but that number seems excessive to me. One more experiment might be to reduce that number (either as a compile-time option or by making it a setup option) and check if it would hurt anything. Already with 32 Full HD images at 4 bytes per pixel it should be possible to run out of the `gpu_mem=256`.

**Comment by reufer** [comment]
> I noticed a constant `OVG_MAX_OSDIMAGES` (256). I may be misunderstanding something, but that number seems excessive to me.

This constant limits the number of images, stored with `cOsdProvider::StoreImageData()` and referenced by a numerical handle for later use. As far as I understand, it's intended to be used for e.g. station logos and other smaller elements, frequently used by the OSD. Of course, you may run out GPU memory quickly, if you store lot of smaller or even few very big images. There's some error handling implemented to catch such cases, but honestly, I haven't tested this under all circumstances.

**Comment by haarm** [comment]
Seit die Auflösung fest auf 1920x1080 einstellt ist, habe ich im Moment keine Probleme mehr.
OSD schließt sich wie es soll, werde es aber noch weiter beobachten.

**Comment by dr-m** [comment]
> > I noticed a constant `OVG_MAX_OSDIMAGES` (256). I may be misunderstanding something, but that number seems excessive to me.
> 
> This constant limits the number of images, stored with `cOsdProvider::StoreImageData()` and referenced by a numerical handle for later use. As far as I understand, it's intended to be used for e.g. station logos and other smaller elements, frequently used by the OSD. Of course, you may run out GPU memory quickly, if you store lot of smaller or even few very big images. There's some error handling implemented to catch such cases, but honestly, I haven't tested this under all circumstances.

Thank you for the explanation. Is there a particular skin or configuration that would display such channel logos?

I think that the worst case with subtitles is that there will be new subtitles displayed every second, or maybe even quicker if the dialogue is tense and the words are short.

So far, I did not notice any ill effect of setting the following:
```diff
diff --git a/ovgosd.c b/ovgosd.c
index 4dc7c59..a6ad4cc 100644
--- a/ovgosd.c
+++ b/ovgosd.c
@@ -1646,7 +1646,7 @@ protected:
 
 /* ------------------------------------------------------------------------- */
 
-#define OVG_MAX_OSDIMAGES 256
+#define OVG_MAX_OSDIMAGES 8
 #define OVG_CMDQUEUE_SIZE 2048
 
 class cOvgThread : public cThread
```
In fact, this patch allows me to view HD channels using `gpu_mem=128`. I did not try a lower setting yet.

If this patch causes some noticeable ill effect, I would be interested in the details. Maybe the memory manager should take the size of each OSD bitmap as well as the total size into account, and/or only cache smaller bitmaps? Assuming that the channel logos are narrow, a simple condition could be that any wide enough OSD bitmap will not be cached.

**Comment by dr-m** [comment]
@haarm Was war Deine ursprüngliche Auflösung? 3840×2160? 7680×4320?

For me, `gpu_mem=64` was too small even for `OVG_MAX_OSDIMAGES` set to 8. VDR failed to start up, and in the log I saw the following:
```
ERROR: driver buffer overflow on device 1
```
With the above patch and `gpu_mem=96`, VDR starts up but it would mostly display a black screen, no subtitles, no OSD (except sometimes the volume settings bar of LCARS) and occasionally some audio. There is some diagnostics for these cases:
```
rpihddevice: [EGL] failed to create pixel buffer surface: bad alloc!
rpihddevice: [OpenVG] failed to create pixmap! (allocation failed)
…
ERROR: 11 TS packet(s) not accepted in Transfer Mode
```
I think that I will use `gpu_mem=128` and the patch from now on, to better test the system near the GPU memory limit.

**Comment by haarm** [comment]
Meine ursprüngliche Einstellung war, Auflösung wie Video

**Comment by dr-m** [comment]
@haarm Ich nehme an, dass es um UHD bzw. 3840×2160 ging. Das ist ja genau die vierfache Anzahl Bildpunkte von HD (1920×1080).

**Comment by haarm** [comment]
Nein, ich habe keine UHD, ganz normale HD und SD Sender

**Comment by dr-m** [comment]
dr-m/rpihddevice@562d61c6d58f320d71723932404cd7fd30e10979 fixes some race conditions around `cOvgThread::m_commands` (between `DoCmd()` and `Action()`). Possibly it will fix the issues for @haarm. It also removes some pointer indirection. I think that some more polling could be replaced with events (untimed waits of condition variables), but I wanted to proceed in small steps.

For me, with those changes and `gpu_mem=128` I ran out of GPU memory, even after setting `OVG_MAX_OSDIMAGES` to 1. I could open and close 2 full-screen OSD menus (hitting the Menu button 4 times) and after that, no OSD would open for HD channels. After switching to an SD channel, I could open a few more full-screen OSD menus, but then the joy was over. With `gpu_mem=192` everything seems to be stable (well, this is still with `OVG_MAX_OSDIMAGES` set to 1). I can’t observe any noticeable delay with that small setting.

**Comment by dr-m** [comment]
I’m not that familiar with the VDR OSD code, but it seems that at most OSD menu can be open at a time. I first suspected it to be an anomaly of my local tweak of `OVG_MAX_OSDIMAGES` to 1, but I observe the same also with a larger value. Easy experiment: Pause and resume the playback of a recording, then hit the Mute button or change the audio volume. No menu for the volume change will pop up (unless you wait long enough after resuming playback). The same could be achieved by changing the multi-lingual audio setting or the subtitle setting in live TV view, and then hitting the Mute button.

**Comment by reufer** [comment]
> Is there a particular skin or configuration that would display such channel logos?

I'm currently not aware of any, it's a rarely used feature of VDR's OSD API.

> I think that the worst case with subtitles is that there will be new subtitles displayed every second, or maybe even quicker if the dialogue is tense and the words are short.

Subtitles, as any other regular OSD elements, use `cPixmap` to draw on. The plugin derives `cOvgPixmap` for an OpenVG accelerated implementation, and uses `cOvgCmdCreatePixelBuffer` to allocate the underlaying `EGL_OPENVG_IMAGE`. There's no hard coded limitation in how many pixmaps can be created, but an error log will indicate, if allocation fails.

> ```diff
> diff --git a/ovgosd.c b/ovgosd.c
> index 4dc7c59..a6ad4cc 100644
> --- a/ovgosd.c
> +++ b/ovgosd.c
> @@ -1646,7 +1646,7 @@ protected:
>  
>  /* ------------------------------------------------------------------------- */
>  
> -#define OVG_MAX_OSDIMAGES 256
> +#define OVG_MAX_OSDIMAGES 8
>  #define OVG_CMDQUEUE_SIZE 2048
>  
>  class cOvgThread : public cThread
> ```

Maybe the name `OVG_MAX_OSDIMAGES` is a bit misleading, but it's solely used for caching images, not for regular OSD elements. So either your skin uses cached images, or you may observe some side effect, if the behavior is different when changing the constant.

**Comment by dr-m** [comment]
@haarm Did dr-m/rpihddevice@562d61c6d58f320d71723932404cd7fd30e10979 improve things for you?

Yesterday, after things initially seemed to work fine with `gpu_mem` reduced to 192 megabytes, attempts to allocate larger OSD surfaces started to fail.

@reufer Thank you for the explanations. I need to read more about this. I have the feeling that once we fail to allocate some GPU memory, it might make sense to release all GPU resources and initialize everything from the scratch, to get rid of any [memory fragmentation](https://en.wikipedia.org/wiki/Fragmentation_(computing)) in the GPU memory allocator(s). I see that `ilclient_enable_port_buffers()` defaults to `vcos_malloc_aligned()`, but I did not figure out yet what `vgCreateImage()` would invoke to allocate memory.

One more thing that might be worth considering is to allocate 1 maximum-resolution pixmap after setting up the video decoding and fonts. If that fails, make the plugin initialization fail. If it succeeds, free the buffer, and make sure that at most one pixmap will be allocated at a time. That should hopefully avoid any memory fragmentation issues. If a cache of multiple pixmaps is really useful (I did not run any profiler yet), then this logic could be revised to: allocate up to N maximum-resolution pixmaps at the start, to determine the maximum size of the pixmap cache.

**Comment by haarm** [comment]
I have now also installed the plugin two of my four Raspi. No problems so far

**Comment by reufer** [comment]
> I have the feeling that once we fail to allocate some GPU memory, it might make sense to release all GPU resources and initialize everything from the scratch, to get rid of any memory fragmentation in the GPU memory allocator(s).

I share your feelings - proper handling of this case is not trivial and honestly, I don't know the correct way to recover.

> One more thing that might be worth considering is to allocate 1 maximum-resolution pixmap after setting up the video decoding and fonts. If that fails, make the plugin initialization fail.

I'm not sure if that's enough. A skin is basically free to create and use as many pixmaps it wants, so this would not prevent from allocation failures, no matter whether it's due to fragmentation or simply lack of memory.

**Comment by dr-m** [comment]
> > I have the feeling that once we fail to allocate some GPU memory, it might make sense to release all GPU resources and initialize everything from the scratch, to get rid of any memory fragmentation in the GPU memory allocator(s).
> 
> I share your feelings - proper handling of this case is not trivial and honestly, I don't know the correct way to recover.

It could indeed be tricky or impractical to implement suitable recovery logic, especially if there is no API for telling the skins or plugins that they should create all pixmaps from the scratch. The main benefit of such recovery logic would be that you could avoid restarting VDR when the GPU memory becomes messed up. A restart would ruin any active recordings.

Sure, if a skin allocates an excessive amount of GPU resources, such recovery logic would not help at all; instead, the system could get into an infinite loop.

I am a little sorry for confusing @haarm’s issue with my similar problem of running out of GPU memory. A separate issue or pull request could be filed later, once it is clearer what could be done.

**Comment by dr-m** [comment]
I am not sure, but I hope that #14 will help a little with the OSD resource management, by synchronizing `CreateSurface()` and `DestroySurface()` with the calling thread.
